# Generated by Django 4.1.10 on 2023-08-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promodel',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='promodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
